### ISSUE TITLE
AP not visible

### ISSUE THREAD

**Issue by redelectrical** [klausahrenberg/WThermostatBeca#101]
My BHT-002 flashes successfully, but with the message "Warning: Image file at 0x0 doesn't look like an image file, so not changing any flash settings.".

No AP appears. Tested using v1.07 and v1.08

If I flash back to original then smartlife AP works so unlikely to be a hardware issue.

Looks the same as issue #70 [https://github.com/klausahrenberg/WThermostatBeca/issues/70](url)

Terminal output below:

$ sudo esptool.py -p /dev/ttyUSB0 erase_flash
esptool.py v2.8
Serial port /dev/ttyUSB0
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: bc:dd:c2:a8:0f:21
Uploading stub...
Running stub...
Stub running...
Erasing flash (this may take a while)...
Chip erase completed successfully in 0.5s
Hard resetting via RTS pin...
sudo esptool.py -p /dev/ttyUSB0 write_flash -fs 1MB 0x0 WThermostat_1.08.bin 
esptool.py v2.8
Serial port /dev/ttyUSB0
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: bc:dd:c2:a8:0f:21
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Warning: Image file at 0x0 doesn't look like an image file, so not changing any flash settings.
Compressed 68800 bytes to 14511...
Wrote 68800 bytes (14511 compressed) at 0x00000000 in 1.3 seconds (effective 430.1 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

**Comment by klausahrenberg** [comment]
Sorry, I can't help at this issue. The warning should not appear during flashing. I never had this issue, if the backup ran fine - also the flashing wasn't an issue.
