### ISSUE TITLE
No option for BHT-002-GCLW (Water/Gas Boiler)

### ISSUE THREAD

**Issue by privatesam** [klausahrenberg/WThermostatBeca#107]
Upon initial configfuration there is no option in the dropdown for BHT-002-GCLW (Water/Gas Boiler).

**Comment by austwhite** [comment]
Use the BHT-002-GAxx. It works identically to the BHT-002-GCxx
The only difference is the GC is dry contact

**Comment by privatesam** [comment]
Great thanks.
