### ISSUE TITLE
Unsuccessful flash

### ISSUE THREAD

**Issue by redelectrical** [klausahrenberg/WThermostatBeca#110]
Regarding being unable to flash the image as in issue #101 . Thanks for your reply to that issue and I think I've got to the bottom of it.

I think this has arisen because esptool.py was updated and now looks for the 'magic byte' at the beginning of the binary (committed in July 2019). I think tuya-convert also checks this.

I have downloaded the binary from [https://github.com/fashberg/WThermostatBeca/releases](url) which flashes with no issue.

Just thought you would want to know.

**Comment by klausahrenberg** [comment]
Thanks for the information
