### ISSUE TITLE
State is always heating

### ISSUE THREAD

**Issue by Bl00d-B0b** [klausahrenberg/WThermostatBeca#125]
Hello,

Why state is always show me heating?
thermostat_31843/thermostat/properties {"idx":"thermostat_31843","ip":"192.168.10.167","firmware":"1.11","temperature":27.00,"targetTemperature":30.00,"deviceOn":true,"schedulesMode":"off","ecoMode":false,"locked":false,"floorTemperature":25.50,"state":"heating"}

thermostat_31843/thermostat/properties {"idx":"thermostat_31843","ip":"192.168.10.167","firmware":"1.11","temperature":27.50,"targetTemperature":20.00,"deviceOn":true,"schedulesMode":"off","ecoMode":false,"locked":false,"floorTemperature":25.50,"state":"heating"}

I set target temperature to +30, and then +20... I see relay works as expected, but status always heating.

Ed

**Comment by fashberg** [comment]
Hey @Bl00d-B0b ,

without the hardware-modification, described at https://github.com/klausahrenberg/WThermostatBeca/issues/17#issuecomment-552078026 the WiFi Module/WThermostat does not really know the state of the relay (controlled by 2nd CPU/MCU)

Check https://github.com/klausahrenberg/WThermostatBeca/blob/master/Configuration.md#1-configure-thermostat-device-model-selection
and disable "HW Mod" option and state will disappear.

Kind Regards
Folke
