### ISSUE TITLE
Support for BHT-1000

### ISSUE THREAD

**Issue by matthewjporter** [klausahrenberg/WThermostatBeca#126]
Hi, 

I have a BHT-1000 UFH thermostat that registers to the Beca energy App and the Smart-Life app and is detected by the HomneAssistant tuya integration

Is is possible this thermostat is suppoorted?

**Comment by fashberg** [comment]
Hey @matthewjporter ,

check out https://github.com/fashberg/WThermostatBeca/issues/31 

Kind Regards
Folke
