### ISSUE TITLE
Network connection icon on screen

### ISSUE THREAD

**Issue by jsponz** [klausahrenberg/WThermostatBeca#128]
Thanks for your nice firmware. It is really great!

Is there any way to show the WiFi status while the thermostat is connected? 

![image](https://user-images.githubusercontent.com/12778286/89789927-8d584f00-db21-11ea-99bd-b4cea03839f8.png)

This icon only appears with the original firmware in the setup phase, but it would be great to have it also on the screen once the device is connected.

**Comment by fashberg** [comment]
Hi @jsponz,

the WiFi-Icon is controlled by the 2nd CPU (MCU) which has still the original Closed-Source Software.

Communication between ESP-Wifi-CPU and MCU is very limited, so there are no enhancements possible.

Like with original Firmware: The WiFi Icon only blinks in recovery-mode 

:(

Kind Regards
Folke
