### ISSUE TITLE
External push button

### ISSUE THREAD

**Issue by cyraxxx** [klausahrenberg/WThermostatBeca#134]
Hello,

First I would like to thank your work with this thermostat family :) I have a BAC-002-ALW, flashed your firmware and works as expected. 

However I couldn't notice that maybe there are some free GPIOs on the ESP and I would like to ask if I can add an emergency external push button that would manually set some conditions (for example, set heating mode, heating temperature to 30C and turn on fan at middle level)? Because in my case I would like to hide the thermostat inside the fan-coil's body and control only by MQTT (I dont have external thermostat terminal and don't want to ruin the walls :D ) 

In this case I could apply a simple button on the fan-coils body and that would guarantee that if network is down, but power and heating/cooling is on, I can still use the device.

**Comment by klausahrenberg** [comment]
Hi, sorry to say, but I will not implement a feature like this. I know, almost all GPIOs are available at the ESP. But if you extend the device in this way, please make a fork of this firmware. I would prefer to implement an emergency button with a separate ESP device over MQTT
