### ISSUE TITLE
Flashing BHT-6000-GALW

### ISSUE THREAD

**Issue by DKBelka** [klausahrenberg/WThermostatBeca#140]
Hi!

I have the BHT-6000-GALW. Does thermostat work with your firmware?

Thank you!

**Comment by barelby** [comment]
The same question - I couldn't flash  GALW :( Is there any soluition?

**Comment by gavlexx** [comment]
Use [fork](https://github.com/fashberg/WThermostatBeca)  instead

**Comment by klausahrenberg** [comment]
It works with BHT-3000 and BHT-6000. It's the same like BHT-002. In new version 1.20 it's added in the device selection.
