### ISSUE TITLE
BHT002 devices can not be flashed anymore

### ISSUE THREAD

**Issue by zimpie** [klausahrenberg/WThermostatBeca#142]
I am experiencing the same problem als in #141. (same BHT0002)
Sadly I connot include the fix from #141 bei myself and can't compile.

Would be cool, if the fix can be integratet in next release!
(can also test, if a bin is provided)
(I was unable to open issue 141, sorry, I am a GIT newbe and dont know best practice in issuehandling...)

**Comment by klausahrenberg** [comment]
If your device is the new one from DLX solutions, it's now supported in 1.20. Please test. Select at thermostat configuration 'DLX-HL01'
