### ISSUE TITLE
NEO Coolcam

### ISSUE THREAD

**Issue by 31warren** [klausahrenberg/WThermostatBeca#147]
I have been unable to get this to work with a Neo Coolcam PIR and the pre-compiled version on Github. Please advise if this version should work or if changes need to have made.

After (wired) flashing the device boots ok and opens the configuration menu. Once configured it sends the following message over MQTT every time it is powered up.

{"idx":"neocoolcam_23564","ip":"192.168.1.157","firmware":"1.18","on":false}

This message is only sent once - no other messages are sent, no matter how long the device is left. It does not respond to movement.

Please advise if I have missed something in the configuration.

**Comment by klausahrenberg** [comment]
Neo Coolcam PIR is a motion sensor, right? This firmware is for a thermostat, not a motion sensor. My other firmware "NeoCoolcam" (https://github.com/klausahrenberg/WNeoCoolcam) that you maybe has flashed on your device, is for a power plug from NeoCoolcam, not for the motion sensor.
