### ISSUE TITLE
BHT6000-GBLW tasmota basic flashed

### ISSUE THREAD

**Issue by Polimac** [klausahrenberg/WThermostatBeca#150]
i wrongly flashed basic tasmota firwmare as i didn't put Wthermostat*.bin in files over tuya-convert
everything works fine regarding tasmota
can you please tell me if there is a option so i can upload yout Beca firmware over tasmota basic
i tried upgrade by file upload in web interface, it says Upload Failed Not compatible

I mean do i need to flesh it manually with wiring or is there a option to do it remotely

Thanks so much in advnace

**Comment by fashberg** [comment]
Hi!

Option78 is your friend: https://github.com/fashberg/WThermostatBeca/blob/master/Flashing.md#option-3-flashing-on-top-of-tasmota-or-other-free-firmware 


Kind Regards
