### ISSUE TITLE
Celsius to Fahrenheit 

### ISSUE THREAD

**Issue by tlmarion** [klausahrenberg/WThermostatBeca#152]
DO you know of a way to change it from Celsius to Fahrenheit in the configuration?

**Comment by danilkorotkov** [comment]
I didn’t see remote configuration in firmware as tuya has. Possible only with manual panel settings

**Comment by klausahrenberg** [comment]
It depends, most devices can only be switched on the device itself. 1 device - I know - that supports the configuration via Tuya - is ME102H. But I didn't implement this in my firmware.
