### ISSUE TITLE
Change sensor.

### ISSUE THREAD

**Issue by dimvia** [klausahrenberg/WThermostatBeca#157]
is it possible to adjust to another temperature sensor? for example 6.8 ntc?

**Comment by pashok2398** [comment]
@dimvia Is it BHT-002 xxxx ?

**Comment by klausahrenberg** [comment]
This is not possible for device BHT-002. If you don't receive some unknown MCU commands at your MQTT broker, than your model will not support sensor selection via remote.
For model ME102H it's implemented now. For model ME81AH it seems possible too - not sure. Which model do you have?

**Comment by klausahrenberg** [comment]
For model ME81AH and ME102H it's now implemented since v1.20j
