### ISSUE TITLE
add some basic API GET requests ?

### ISSUE THREAD

**Issue by phil31** [klausahrenberg/WThermostatBeca#161]
Hi, great my device seem working with this firmware :o)
thanks guy

i wondering why only MQTT support ? 
why not add a simple API to command the device with GET or POST http requests ?
this will be usefull to integrate the device into home automation, without requiring an MQTT broker !?
i'm using JEEDOM, which can perfectly manage http requests !

i looking to the code, but unfortunatly, C++ is not for me !

thanks for any update, regards

**Comment by klausahrenberg** [comment]
No problem, with webthings this functionality is already included:
GET requests:
`//<thermostatIP>/things/thermostat/properties/deviceOn` gives the actual state for property deviceOn as json
PUT requests:
`//<thermostatIP>/things/thermostat/properties/deviceOn` and content as json, e.g. `{"deviceOn": false}`
