### ISSUE TITLE
Manual restart

### ISSUE THREAD

**Issue by helmar74** [klausahrenberg/WThermostatBeca#164]
Hi, one of my thermostat isn't connected to WIFI, how ever...

Is there a possbility to manual restart the device (e.g. pressing some buttons together) or do I have to powercycle it?
(All oy my thermostats and the complete heating are in one power circuit...)

Or is there a possbility to manual connect to wifi with button press on the device?

Thanks a lot for your great work!

**Comment by klausahrenberg** [comment]
You can restart the device in the web interface (Menu reboot)
