### ISSUE TITLE
Wifi disconnect after a few days

### ISSUE THREAD

**Issue by JFingerle** [klausahrenberg/WThermostatBeca#168]
After a few days my BHT-002-GBLW disconnects from Wifi. To fix it I need to power cycle the thermostat. In my memory this didn't happen with the very first firmware release. It appeared after I upgraded to a newer firmware which introduced had the Mozilla Webthings API.
My router reboots automatically every night at 4am. The last disconnects happened at 11:22am and 8:00am - so I don't think it has anything to do with the reboots.

Maybe this can be fixed by disabling the "wifi sleep mode" as written here?
https://github.com/esp8266/Arduino/issues/5083

**Wifi & router information**
- Frequency: 2.4GHz
- Distance: ~3m
- Router: Archer C5 v1, OpenWrt 18.06.4, only 2.4GHz enabled - 5GHz is disabled

**Comment by klausahrenberg** [comment]
Hi, I have several devices running with mozilla webthings - also with unstable wifi connections. Devices, that are far away from router, sometimes disconnect and should reconnect automatically. For my devices this works really good and I had some work to make this behavior reliable.
From version 1.20 on I rewrote the connection/reconnection again in some parts. Now the firmware trys a reconnect after 50 seconds for 3 times. After that, the AccessPoint for configuration will be reopen for configuration. Test and take a look, if the thermostat reopens an AccessPoint after some time. If this is the case, the thermostat has a critical distance to your router.
