### ISSUE TITLE
MQTT targetTemperature

### ISSUE THREAD

**Issue by pawelkli** [klausahrenberg/WThermostatBeca#170]
Hi,
Avatto ME81H/WThermostatBeca 1.8

Manual targetTemperature change is not announced (except reboot). 
Request http returns the correct value

**Comment by klausahrenberg** [comment]
Yes, known issue - sometimes state changes are not reported by MQTT immediately. I will have a look at this in new year.

**Comment by klausahrenberg** [comment]
Reason for bug detected. Will be fixed from 1.20d on - just wait one or 2 days. Thanks for understanding.

**Comment by klausahrenberg** [comment]
Fixed since 1.20. Notice, the version needs some further testing - still alpha status.
