### ISSUE TITLE
Version Error 1.19 vs 1.16

### ISSUE THREAD

**Issue by helmar74** [klausahrenberg/WThermostatBeca#176]
Is there a version error in the repo?
![image](https://user-images.githubusercontent.com/25499089/104091345-16181a00-527d-11eb-820b-0ef615ebbade.png)

**Comment by klausahrenberg** [comment]
No, it's a typo from me in my commit message.

This is version 1.19 definitely

**Comment by helmar74** [comment]
So I can update my Thermostats?
Are there any breaking changes?

**Comment by klausahrenberg** [comment]
No breaking changes between 1.18 and 1.19. You can update, no functional changes, only improved reliability.

**Comment by helmar74** [comment]
Thanks for the info.
Updated my 8 GBLW's to Version 1.19:
![image](https://user-images.githubusercontent.com/25499089/104093170-1c13f800-5289-11eb-8fd8-7f0175fadce6.png)



Thank you for your good work!!!!!
