### ISSUE TITLE
ME81AH - targetTemperature divided by 10

### ISSUE THREAD

**Issue by dimerr** [klausahrenberg/WThermostatBeca#180]
1.20d brought this:

warmfloor/thermostat/properties {"idx":"warmfloor","ip":"192.16.1.247","firmware":"1.20d","temperature":24.50,"targetTemperature":4.00,"floorTemperature":0.00,"deviceOn":true,"sched

while it is set to 40 degrees

**Comment by klausahrenberg** [comment]
fixed hopefully now in version 1.20e
