### ISSUE TITLE
firmware >1.18 Not saving option "Send changes in separate MQTT messages"

### ISSUE THREAD

**Issue by EugenePanyaev** [klausahrenberg/WThermostatBeca#183]
ME81AH model

**Comment by lozb36** [comment]
I guess it saves the configuration, but does not select the checkbox in web-interface after refreshing the page.
The same error appears with network ->Advanced MQTT options. The options were set correct, but it does not show up.

**Comment by klausahrenberg** [comment]
> firmware >1.18 Not saving option "Send changes in separate MQTT messages"

corrected in v1.20j. Thanks for reporting.
