### ISSUE TITLE
[Feature Request] Sending data to the blynk server

### ISSUE THREAD

**Issue by newex1968** [klausahrenberg/WThermostatBeca#184]
Excellent work! Thank you

I would like to suggest adding a function for sending temperature data to the Blink server.
This is more convenient in many cases.

Thanks again for your project

**Comment by klausahrenberg** [comment]
Hi, sorry, but blynk will not be implemented additionally to MQTT and Webthings support. It's a good idea, but I would suggest a separate fork for this.
