### ISSUE TITLE
[Feature Request] Timer for OFF after some time

### ISSUE THREAD

**Issue by fabitom** [klausahrenberg/WThermostatBeca#185]
I would like to have a timer feature that would turn off the thermostat 1 hour after it's been turned on.
I know that all thermostat based on targetTemperature but I've floor heating as a second additional heating source. My gas stove keep house temperature but floor is addition (to have warm floor), so I always need to remember to turn off.
Tasmota have that feature in command PulseTime.

Thanks.

**Comment by klausahrenberg** [comment]
This firmware is focused on support for MQTT and Webthings. Your request could easily implemented in your MQTT broker via node-red. In Webthings you can define a rule to switch off the thermostat after 1h. There you can also consider other parameters to turn the device on or off.
