### ISSUE TITLE
ME81H pictures for documentation

### ISSUE THREAD

**Issue by Gulpman** [klausahrenberg/WThermostatBeca#188]
Hi, 
I ordered a ME81H - after some search on this page I found out that it should be the same as the ME81AH mentioned here. Searching the docs I fould pics from other thermostats but not from the ME81H.

I did some pics and hope they are helpful for the documentation.

![IMG_20210128_163142](https://user-images.githubusercontent.com/7381871/106166555-95b64c00-618c-11eb-8162-a6aefc094497.JPG)
![IMG_20210128_163238](https://user-images.githubusercontent.com/7381871/106166578-9c44c380-618c-11eb-9621-dd520e4d9f02.JPG)
![IMG_20210128_163249](https://user-images.githubusercontent.com/7381871/106166603-a23aa480-618c-11eb-89e1-b3627df680a1.JPG)
![IMG_20210128_163800](https://user-images.githubusercontent.com/7381871/106166620-a5359500-618c-11eb-980b-8b78d571f862.JPG)
![IMG_20210128_163810](https://user-images.githubusercontent.com/7381871/106166635-a9fa4900-618c-11eb-9a92-80146bf998ea.JPG)
![IMG_20210128_170157](https://user-images.githubusercontent.com/7381871/106166653-ae266680-618c-11eb-97fe-a31a9db34bd9.JPG)

I will do the soldering and flashing on the weekend. :) If I understood correctly, I must use V1.20 for this thermostat. 

Best 
Sascha

**Comment by klausahrenberg** [comment]
Thanks for the pictures, I will add it to the docs. Yes, for this Thermostat use the latest firmware of 1.20. However, it seems that the support isn't fully working yet. I don't own this one, so every feedback is welcome to finish the implementation for this device.

**Comment by Elwell** [comment]
I've just ordered one of these and noticed the board rev has gone up to 1.2. Picture at https://twitter.com/elwell2000/status/1394228472541679617/photo/1

**Comment by tsrubar** [comment]
> I've just ordered one of these and noticed the board rev has gone up to 1.2. Picture at https://twitter.com/elwell2000/status/1394228472541679617/photo/1

Indeed, i can confirm that. New design doesnt have underlight power button and print seems  cheap on these
![Uploading IMG_20210511_142635.jpg…]()
