### ISSUE TITLE
MQTT Port

### ISSUE THREAD

**Issue by dionisor** [klausahrenberg/WThermostatBeca#19]
Hi Klaus,
Thank you for excellent fw!!!!
It would be possible to include "MQTT Port" in configuration form "Configure Device"? It would be nice.

Thanks!!!!
Best regards

**Comment by Bettman66** [comment]
[https://github.com/klausahrenberg/ThermostatBecaWifi/pull/31](url)

**Comment by klausahrenberg** [comment]
I will add the mqtt port in future version

**Comment by klausahrenberg** [comment]
MQTT port now supported in version 0.98. Please take attention to following: 
- After update all settings must be reconfigured
- MQTT topics has changed completely between v0.95 and later, see Readme.md for new json structure
