### ISSUE TITLE
Any of GPIO is usable the TYWE3S if i use this device?

### ISSUE THREAD

**Issue by vampywiz17** [klausahrenberg/WThermostatBeca#196]
Hello there,

I would like to connect to the ESP module a OpenTherm adapter. It need two free GPIO (one of interrupts) it possible to do this or it use all GPIO?

**Comment by klausahrenberg** [comment]
This device only use RX/TX and sometimes 1 GPIO for Wifi State. So almost all GPIOs on the ESP are available
