### ISSUE TITLE
mqtt error message

### ISSUE THREAD

**Issue by kopakte** [klausahrenberg/WThermostatBeca#199]
In version 1.20l BHT-002 continuously sends a mqtt message {"error":"Unknown MCU command: 55 aa 01 07 00 05 68 01 00 01 01"}. What does this mean?

**Comment by klausahrenberg** [comment]
Yepp, not an issue. This informs only that a message from the MCU was ignored. I removed a flag to hide in last version / this flag will be added again from v1.20n on, the the message will not appear again. You can ignore this message.
