### ISSUE TITLE
Is possible add other functions?

### ISSUE THREAD

**Issue by petr-vytlacil** [klausahrenberg/WThermostatBeca#219]
Hi,
is possible add other functions? Change UI, add buttons example for calling URLs (REST API). It could also serve as an interface for controlling blinds, shutters via LOXONE.

THX

**Comment by klausahrenberg** [comment]
Hi, it's not planned to add many further functions. REST API is supported via Webthings support. That means, you can control the thermostat via HTTP properties. 
Functional extensions for the WEB-UI to control the thermostat (buttons etc) are not planned. UI is only for configuration of the device. This firmware provides support for MQTT and Webthings, any automation functions etc. should be done within these 2 systems.
