### ISSUE TITLE
Is TYWE3S replaceable by esp8266 in tuya ME81H?

### ISSUE THREAD

**Issue by ikke-t** [klausahrenberg/WThermostatBeca#269]
Hi,

I got fooled while ordering ME81H from ebay. They shipped me with no-wifi version. It looks like all components but tywe3s are on board. I was wondering if I could just solder esp8266 from some developer board that I have in place of missing tywe3s and flash this fir,ware?

Is there any change it could work? For the existing pins they lpook compatible, esp has few more.

https://tasmota.github.io/docs/devices/TYWE3S/
https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/

Any experience or knowleqge?

**Comment by ikke-t** [comment]
Updating this for the next one:

So I received no-wifi version:
![no ESP](https://user-images.githubusercontent.com/1146409/187263106-5909335d-d984-4c59-9668-6619a9a6f58e.jpg)

And I flashed this FW to Wemos D1 mini, and soldered off the ESP12 and soldered it to this board:
![with ESP](https://user-images.githubusercontent.com/1146409/187263417-f4a61d88-c4e1-426c-903f-82ed5ba7f49d.jpg)

The latter image also has the relay state mod with voltage divider.

And it seems to work fine! Great. Now to study the features of this FW, thanks for all the work on it. Seems to work fine so far.

**Comment by ikke-t** [comment]
Just soldered another one. Works fine too. Great :D

**Comment by g6094199** [comment]
Hi
i also have a rev 1.4 and would like to do the relay mod. can you explain a bit more whats under the tape. is there a divider or just a single R? what size?

**Comment by ikke-t** [comment]
I recall it's just a resistor, not sure. I don't remember the size. There is another issue about relay state reading, I likely copied the setup from there.

https://github.com/klausahrenberg/WThermostatBeca/issues/17

**Comment by ikke-t** [comment]
Hei @g6094199 now that I look it better, I remember. It's divider. See how I put the oyher resistor directly to esp32 pin at the other end of wire.

**Comment by g6094199** [comment]
hmm...but the devider must be pulled to gnd somewhere.  maybe unter the shrink somewhere?
anyway. ill put in  a divider  tomorrow.

**Comment by ikke-t** [comment]
Yes, the other resistor from the end of wire goes to groud. Look with zoom, it's under the wire.

**Comment by g6094199** [comment]
ahhhhhh....now i see it! ;-)
