### ISSUE TITLE
Unable to Flash Beca BAC-6000

### ISSUE THREAD

**Issue by mojtabavi** [klausahrenberg/WThermostatBeca#284]
I'm Trying to flash beca BAC-6000 thermostat using CH340G device
But the desired esp module is not placed in the program mode and sends incomprehensible characters on the serial
ESP Model:
TYWE3S
Connection:
esp-gnd --> gnd
esp-3v3 --> 3v3
esp-gpio0 --> gnd
esp-rx --> tx
esp-tx --> rx
![Screenshot 2022-12-01 141155](https://user-images.githubusercontent.com/63472358/205035170-494c0444-004e-46e3-ab42-adbbb9212539.png)
![photo_2022-12-01_14-09-15](https://user-images.githubusercontent.com/63472358/205035193-81c4bdc7-7912-45bd-9bf7-272a1ccb1e61.jpg)

I'm really confused, I'd really appreciate it if someone could help

**Comment by mojtabavi** [comment]
https://user-images.githubusercontent.com/63472358/205035911-6b0a889b-5282-4a95-8274-f76a5ea50865.mp4

**Comment by jfjeronimo** [comment]
could you share the solution ? I have the same problem
