### ISSUE TITLE
v1.34 returns json rather than html

### ISSUE THREAD

**Issue by richard-scott** [klausahrenberg/WThermostatBeca#294]
After setting the network settings, the UI show JSON data, rather than HTML.
Is that right? I can get to the config menu by adding /config/ to the URL, but on the last firmware that was automatic.

<img width="412" alt="Screenshot 2023-03-15 at 10 01 29" src="https://user-images.githubusercontent.com/5149834/225275539-31eb43d9-387f-4ddc-8729-ae1399a081e3.png">

**Comment by klausahrenberg** [comment]
Yes, this is right behavior. To access the web interface  for configuration, you have to add /config. Reason is support of webthing. The device description must be provided at root of web server.
