### ISSUE TITLE
Can't save DST settings

### ISSUE THREAD

**Issue by dwarning** [klausahrenberg/WThermostatBeca#298]
I am using the fork from AlbertWeterings v1.0.11 Beta. Because the timezone via internet is not working (see #297) I used fixed UTC offset and DST calculation. The problem is that the DST settings 0,3,0,0,2 are not saved after pressing "Save configuration" button. There comes anytime 0,183,4,174,4 after boot - as shown in the pictures.
![Bildschirmfoto vom 2023-03-26 18-03-40](https://user-images.githubusercontent.com/18441932/227789030-5015b9a9-c94e-4527-9563-65233e88cd4b.png)
![Bildschirmfoto vom 2023-03-26 18-01-42](https://user-images.githubusercontent.com/18441932/227789039-e35a06b0-8db5-42fb-bdd6-b32ef6401e5a.png)

**Comment by klausahrenberg** [comment]
Failure in DST settings (Failure in byte array saving) fixed in v1.35
