### ISSUE TITLE
Direct control of a sonoff reley running tasmota?

### ISSUE THREAD

**Issue by multijohn** [klausahrenberg/WThermostatBeca#30]
Hello,
Because i'm not yet have a running mqtt broker, i like to control an additional remote relay via wifi, directly from this thermostat. 
Is it possible?
I'm seeing that http websend is not supported!
thank you.

**Comment by klausahrenberg** [comment]
Not possible yet. Have to think about it, maybe in future

**Comment by klausahrenberg** [comment]
Hi, sorry, I will not implement this feature. I think, it's easier to realize your wish with MQTT. I recommend to do this with node-red. Best regards
