### ISSUE TITLE
Not an issue - Tuya-Convert

### ISSUE THREAD

**Issue by cclein** [klausahrenberg/WThermostatBeca#38]
I had a thermostat from Moeshouse from last year that I was able to convert via TuyaConvert.

Bought 2 more a week ago. I had to upgrade my version of Tuya-Convert but was successful in rewriting my firmware with the latest TuyaConvert. The packaging was different, smaller box.

**Comment by ivanmarban** [comment]
@cclein so you were able to install WThermostatBeca binary file firmware using TuyaConvert without wiring, right ?

**Comment by cclein** [comment]
That is correct. First one I did I used the included tasmota firmware then to the thermostat firware, but 2nd one I copied the WThermostatBeca bin into the files directory and went from there.
