### ISSUE TITLE
Tasmota 7

### ISSUE THREAD

**Issue by baha00** [klausahrenberg/WThermostatBeca#44]
Not an issue just warning, do no load this firmware if you have tasmota v7 already loaded...

**Comment by cclein** [comment]
What happens?

**Comment by klausahrenberg** [comment]
Please explain the issue, I can't see any problem. Actually you can load my firmware via Upload function of Tasmota and you can go back to Tasmota via Upload function of my firmware. I tested this last week with latest Tasmota 7 nightly/developer without any issue.

**Comment by cclein** [comment]
Using the latest tuya-convert I'm pretty sure I ended up with version 7 on my thermostat before loading this firmware. I experienced no ill effects. What should I be looking out for?

**Comment by baha00** [comment]
HI all update. Thermostat entered in lock mode. holding up&down arrow turns off lock mode and power&down arrow activates hotspot. No issue here just stupid user= ME
