### ISSUE TITLE
Command List

### ISSUE THREAD

**Issue by MGPhil** [klausahrenberg/WThermostatBeca#50]
Hi,
I am trying to make the BECA thermostats directly compatible with Apple Homekit.
As there is a very good GIT to get the ESP-01/ESP8266 as a Homekit Device WITHOUT gateways.
(https://github.com/maximkulkin/esp-homekit-demo)

What would help me a lot is a complete command list
of what the ESP8266 module can send and receive from the thermostats main controller.

Do you have something like that which you could share with me?

Thanks
Philipp

**Comment by klausahrenberg** [comment]
Hi,
Get started here: I translated a chinese information about the protocol first:
https://github.com/klausahrenberg/WThermostatBeca/blob/master/docs/MCU-Manual-ENG_Tuya.pdf
Then I monitored the commands itself on a serial monitor, written here (sorry, not ordered):
https://github.com/klausahrenberg/WThermostatBeca/blob/master/docs/MCU-Commands_own_overview.pdf
All you need for implementation of commands you can take out of my sources (function `processSerialCommand()` is a good start):

In general (MCU = thermostat main controller):
- Messages coming from MCU have the same format like the one that your firmware has to use to set parameters at the MCU - only the header is different (see my documents)
- Your firmware has to send a heartbeat signal to MCU to keep communication alive

Good start at implementing.
