### ISSUE TITLE
not issue, question: Hardware modification

### ISSUE THREAD

**Issue by iMike78** [klausahrenberg/WThermostatBeca#56]
Hello guys!
Could anyone explain the hardware modification? The connections, resistance, from where to where, etc. :) I'm not dumb, I saw the pictures earlier (anyway I can't find it now), but I'd like to be sure what to do and how to do.
Cheers

**Comment by realthk** [comment]
You can find it in the [config doc](https://github.com/klausahrenberg/WThermostatBeca/blob/master/Configuration.md).

**Comment by iMike78** [comment]
Thank you, I have it done now :)
