### ISSUE TITLE
Strange behaiver at one device (1 of 6)

### ISSUE THREAD

**Issue by lokidaibel** [klausahrenberg/WThermostatBeca#60]
I have patched one device with the latest Firmware. The second one start to make problems.
It seams the displas is overheating.

I dont thing it has something todo with the Firmware. Maybe i reconnected it wron to the backplane.

Just want be extra sure before patching my other 4 devices thats this has nothing todo with the 1.00.

Anyone else see this ?

Greetings

Lukas

**Comment by klausahrenberg** [comment]
For sure this firmware will not have any electrical effect on your device. That can I say for sure. Control of device is always done by internal MCU controler and has nothing to to with the Tyua-'Wifi'-Controler that is flashed by this firmware.
