### ISSUE TITLE
Request: DeviceState to represent heating or idle ?

### ISSUE THREAD

**Issue by austwhite** [klausahrenberg/WThermostatBeca#66]
I am using this and was wondering if it is possible to have the "state" field represent the actual device state, whether it is heating or idle rather than just saying "heating" all the time, irrelevant of device state.

I am using the BHT-002-GCLW model.

**Comment by realthk** [comment]
As it is [in the config doc](https://github.com/klausahrenberg/WThermostatBeca/blob/master/Configuration.md), you have to do a hardware mod first to get the state.

**Comment by austwhite** [comment]
I missed that one. Thanks for that.  Will close this off :)
