### ISSUE TITLE
Q: Enhancement: any plans to support MQTT TLS?

### ISSUE THREAD

**Issue by 08-15at** [klausahrenberg/WThermostatBeca#69]
Thank you for supporting the BAC-Thermostats, stumbled upon it and had to get one and everything worked immediately.
However i've secured all my (Tasmota etc.) devices using TLS. Seems as there should be enough ressources (memory etc.) left to link with bearSSL.
Are there any plans in this direction ?
thanks

**Comment by klausahrenberg** [comment]
Hi, sorry, I don't plan this feature. Resources or especially memory is very limited on these devices already.

**Comment by 08-15at** [comment]
thanks anyway for investigating this, made an internal workaroun for TLS. My thermostat is working fine since months now, I appreciate your efforts.
