### ISSUE TITLE
Support EMER (emergency) mode on BHP-6000

### ISSUE THREAD

**Issue by diabl0w** [klausahrenberg/WThermostatBeca#72]
The BHP-6000 has an Auto and Emergency mode in addition to the Heat and Cool modes that are currently available. Personally, I only need emergency mode set up, but it would be nice to get both modes available.
Source: https://images-na.ssl-images-amazon.com/images/I/C135e3sctjS.pdf

**Comment by klausahrenberg** [comment]
Sorry, I don't own the device and can not buy it. This feature I can not support. You have to track the serial commands send out by device (are there any unknown MCU commands at MQTT broker?). With theses information I could try. If there are no unknown commands, I can not help.
