### ISSUE TITLE
Wrong Temperature Set

### ISSUE THREAD

**Issue by diabl0w** [klausahrenberg/WThermostatBeca#74]
When setting temperature via mqtt, whatever temperature I set to, it sets the thermostat to double that. Example, I set home/things/thermostat/targetTemperature to "70", then it says my thermostat to 140!

**Comment by klausahrenberg** [comment]
Can not reproduce on my model. On my model all values are doubled to realize temperature steps of 0.5 degree. Has your model maybe only 1.0 degree steps? Please tell me your model.

**Comment by diabl0w** [comment]
my model is the bhp-6000, I have since moved to tasmota because I was able to figure out the tuyamcu commands to get all functionality of my device. thank you anyway
