### ISSUE TITLE
Original firmware

### ISSUE THREAD

**Issue by csaboka21** [klausahrenberg/WThermostatBeca#76]
Does anyone got the original firmware?

**Comment by diabl0w** [comment]
the flashing directions tell you to backup the original firmware (as you should always be doing anyway)

**Comment by csaboka21** [comment]
Wow really? :) I'm asking because it got lost...

**Comment by mssaleh** [comment]
This is my backup for BAC-002-ALW model
[https://github.com/mssaleh/WThermostatBeca/blob/master/firmware-BAC-002-ALW.bin?raw=true](url)

**Comment by klausahrenberg** [comment]
[defaultFirmware.zip](https://github.com/klausahrenberg/WThermostatBeca/files/4413963/defaultFirmware.zip)

This is my original backup of model BHT-002-GBLW
