### ISSUE TITLE
which thermostat

### ISSUE THREAD

**Issue by bwired-nl** [klausahrenberg/WThermostatBeca#79]
Hi Klaus
can you help me pointing which thermostat i can buy that can follow you manual exact?
On aliexoress i find many, but the have diff esp
I now have the BEOK but its different also
Thanks!

**Comment by tibo888** [comment]
i buy this one on AliExpress and work perfectly
WiFi Thermostat Moeshouse BHT-002-GBLW(Wifi)

**Comment by austwhite** [comment]
Yes.  That is an identical thermostat just under a different name.

**Comment by klausahrenberg** [comment]
Already answered :-)
