### ISSUE TITLE
Set systemMode not working on BAC-6000-ELW

### ISSUE THREAD

**Issue by zalke** [klausahrenberg/WThermostatBeca#80]
I have the above referenced model, all setting work except changing from heat to cool,

I tried with Tasmota and the following commands work just fine

```TuyaSend4 102,00```
Sets the mode to Cool

```TuyaSend4 102,01```
Sets the systemMode to Heat

**Comment by klausahrenberg** [comment]
Please try version 1.02. If your device reported the correct states, but you was not able to set the modes, than the new version will help.

**Comment by zalke** [comment]
@klausahrenberg 

I'm please to inform that the current version it is working correctly.

Thanks so much for your great work,

BTW is the any way to change from Celsius to Fahrenheit on these thermostats?

**Comment by klausahrenberg** [comment]
That's nice to hear that it's working now. 

According to the manual, you can't switch device to  Fahrenheit
