### ISSUE TITLE
idx Number

### ISSUE THREAD

**Issue by TwoLeftFeet** [klausahrenberg/WThermostatBeca#9]
I am using the Library successfully on a  BTH-002-GBLW central heating thermostat / controller.
I have managed to decode and send MQTT messages.
The inclusion of a "idx" number that is used in Domoticz included in your setup screen would be very useful.
I could then control the unit from within Domoticz.
Thanks for your work...

**Comment by klausahrenberg** [comment]
I will added the idx already in the next bigger update - which will support Mozilla Webthings additionally. But it still need some time - it's to buggy at the moment.

**Comment by klausahrenberg** [comment]
Sorry for late realization. Now the heating season starts, an update will come within the next weeks.

**Comment by TwoLeftFeet** [comment]
Thank you very much for letting me know.....

**Comment by TwoLeftFeet** [comment]
Thank you for the update.
I wonder if you had a chance to add the IDX number for use in Domoticz

**Comment by klausahrenberg** [comment]
Yes, I'm already at testing, but it needs some more days

**Comment by klausahrenberg** [comment]
Hi, I uploaded version 0.96. Please notice that a lot of things changed, e.g., MQTT topic structure. Your idx number is now added, but you have to reconfigure your topics maybe. Descriptions are not finished yet, I started here: https://github.com/klausahrenberg/WThermostatBeca/blob/master/Configuration.md

**Comment by TwoLeftFeet** [comment]
Thank you very much for all your hard work have a lovely Christmas.On 10 Dec 2019 08:09, klausahrenberg <notifications@github.com> wrote:Hi, I uploaded version 0.96. Please notice that a lot of things changed, e.g., MQTT topic structure. Your idx number is now added, but you have to reconfigure your topics maybe. Descriptions are not finished yet, I started here: https://github.com/klausahrenberg/WThermostatBeca/blob/master/Configuration.md

**Comment by klausahrenberg** [comment]
Implemented since 0.96

**Comment by RoboPolaris** [comment]
Hello Klaus,

that all amazing work what you did with Beca. I would like to insert a buffer battery like a supercapacitor onto the bac-002 board which is part of the Beca Thermostat. I figured out that in the board (of the display with the microcontroller) there are 3 pins open, and 2 of it leads to VSS and VDD of the Mikrocontroller SONIX SN8F57084SG. Maybe this is dedicated to be the option to do exactly this. Do you have any experiences to electrical backup the system that after a loss of energy it is not necessary all the time to set up the system again? Thank you very much!

**Comment by pery777** [comment]
Hey, can you please write me how you set up the domoticz to talk to the thermostat?  Where and which idx should be entered?  I would be grateful for help.
