### ISSUE TITLE
How look the Display over the Keys?

### ISSUE THREAD

**Issue by wlan4you** [klausahrenberg/WThermostatBeca#97]
Hello,
wow, great Project. I want to buy this BHT-002-GBLW.
My old AEG electrical control is very boring and the TIME is running up after some weeks.

Great are, that i can put TASMOTA on the Firmware.
But, how is looking the front Display and the Keys?
Can you make some Picture from this ?

Thank You
Stefan
Or you can send it to me by email.
Greetings from Germany

**Comment by fashberg** [comment]
hi! 
Check out here: https://github.com/fashberg/WThermostatBeca/blob/master/docs/device.jpg

changing the firmware will not change the behaviour on the display and keys. 
Not possible. Why: https://github.com/fashberg/WThermostatBeca/#hardware

Kind Regards from Munich

Folke

**Comment by klausahrenberg** [comment]
Nothing to add to comments from @fashberg
