### ISSUE TITLE
Tasmota 8.2.0 to WThermostatBeca 1.0.4 update

### ISSUE THREAD

**Issue by SeTeM** [klausahrenberg/WThermostatBeca#98]
Hi,

I tried to migrate to this firmware from Tasmota 8.2.0, but the update failed:
![image](https://user-images.githubusercontent.com/461480/79855809-1f521580-83d4-11ea-969c-4624334ce9d1.png)

I saw several related issues in the repository, but they say it should work with Tesmota 7.X version. How else can I migrate the firmware?

I also tried WThermostatBeca 1.0.3, but without luck.
Could a note "Major change in parameter storage layout" between 7.X and 8.X releases of Tasmota point at the problem?

Thermostat: MoesHouse BHT-002-GBLW

**Comment by SeTeM** [comment]
A downgrade to Tasmota 7.2-minimal allowed me to update the firmware to WThermostatBeca 1.0.4.

**Comment by austwhite** [comment]
The reason for this is because these thermostats only have 1Mb memory.
🙂
